// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reward/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterVeContractReward struct {
	Creator           string                                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Contract          string                                 `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	GasFeeShares      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=gas_fee_shares,json=gasFeeShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gas_fee_shares"`
	BlockRewardShares github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=block_reward_shares,json=blockRewardShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"block_reward_shares"`
}

func (m *MsgRegisterVeContractReward) Reset()         { *m = MsgRegisterVeContractReward{} }
func (m *MsgRegisterVeContractReward) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterVeContractReward) ProtoMessage()    {}
func (*MsgRegisterVeContractReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_837cc604acddc9f4, []int{0}
}
func (m *MsgRegisterVeContractReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterVeContractReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterVeContractReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterVeContractReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterVeContractReward.Merge(m, src)
}
func (m *MsgRegisterVeContractReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterVeContractReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterVeContractReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterVeContractReward proto.InternalMessageInfo

func (m *MsgRegisterVeContractReward) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterVeContractReward) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type MsgRegisterNProtocolReward struct {
	Creator           string                                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Contract          string                                 `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	GasFeeShares      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=gas_fee_shares,json=gasFeeShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"gas_fee_shares"`
	BlockRewardShares github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=block_reward_shares,json=blockRewardShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"block_reward_shares"`
}

func (m *MsgRegisterNProtocolReward) Reset()         { *m = MsgRegisterNProtocolReward{} }
func (m *MsgRegisterNProtocolReward) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterNProtocolReward) ProtoMessage()    {}
func (*MsgRegisterNProtocolReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_837cc604acddc9f4, []int{1}
}
func (m *MsgRegisterNProtocolReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterNProtocolReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterNProtocolReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterNProtocolReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterNProtocolReward.Merge(m, src)
}
func (m *MsgRegisterNProtocolReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterNProtocolReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterNProtocolReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterNProtocolReward proto.InternalMessageInfo

func (m *MsgRegisterNProtocolReward) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterNProtocolReward) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type MsgRegisterRewardResponse struct {
}

func (m *MsgRegisterRewardResponse) Reset()         { *m = MsgRegisterRewardResponse{} }
func (m *MsgRegisterRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRewardResponse) ProtoMessage()    {}
func (*MsgRegisterRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837cc604acddc9f4, []int{2}
}
func (m *MsgRegisterRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRewardResponse.Merge(m, src)
}
func (m *MsgRegisterRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRewardResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterVeContractReward)(nil), "evmos.v9.reward.MsgRegisterVeContractReward")
	proto.RegisterType((*MsgRegisterNProtocolReward)(nil), "evmos.v9.reward.MsgRegisterNProtocolReward")
	proto.RegisterType((*MsgRegisterRewardResponse)(nil), "evmos.v9.reward.MsgRegisterRewardResponse")
}

func init() { proto.RegisterFile("reward/tx.proto", fileDescriptor_837cc604acddc9f4) }

var fileDescriptor_837cc604acddc9f4 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x2d, 0x4f,
	0x2c, 0x4a, 0xd1, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0x2d, 0xcb,
	0xcd, 0x2f, 0xd6, 0x2b, 0xb3, 0xd4, 0x83, 0xc8, 0x48, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0xe5,
	0xf4, 0x41, 0x2c, 0x88, 0x32, 0xa5, 0x4e, 0x26, 0x2e, 0x69, 0xdf, 0xe2, 0xf4, 0xa0, 0xd4, 0xf4,
	0xcc, 0xe2, 0x92, 0xd4, 0xa2, 0xb0, 0x54, 0xe7, 0xfc, 0xbc, 0x92, 0xa2, 0xc4, 0xe4, 0x92, 0x20,
	0xb0, 0x2e, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xfc, 0x22, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0x23, 0x19, 0xaa, 0x56, 0x82, 0x09, 0x2c,
	0x05, 0xe7, 0x0b, 0x85, 0x70, 0xf1, 0xa5, 0x27, 0x16, 0xc7, 0xa7, 0xa5, 0xa6, 0xc6, 0x17, 0x67,
	0x24, 0x16, 0xa5, 0x16, 0x4b, 0x30, 0x83, 0x54, 0x38, 0xe9, 0x9d, 0xb8, 0x27, 0xcf, 0x70, 0xeb,
	0x9e, 0xbc, 0x5a, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x72, 0x7e,
	0x71, 0x6e, 0x7e, 0x31, 0x94, 0xd2, 0x2d, 0x4e, 0xc9, 0xd6, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6,
	0x73, 0x49, 0x4d, 0x0e, 0xe2, 0x49, 0x4f, 0x2c, 0x76, 0x4b, 0x4d, 0x0d, 0x06, 0x9b, 0x21, 0x14,
	0xc7, 0x25, 0x9c, 0x94, 0x93, 0x9f, 0x9c, 0x1d, 0x0f, 0xf1, 0x11, 0xcc, 0x68, 0x16, 0xb2, 0x8c,
	0x16, 0x04, 0x1b, 0x05, 0xf1, 0x25, 0xc4, 0x7c, 0xa5, 0x0e, 0x26, 0x2e, 0x29, 0xa4, 0xb0, 0xf0,
	0x0b, 0x00, 0x85, 0x50, 0x72, 0x7e, 0xce, 0x08, 0x0c, 0x0a, 0x69, 0x2e, 0x49, 0xa4, 0x90, 0x80,
	0x48, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x1a, 0xbd, 0x67, 0xe4, 0x62, 0xf6, 0x2d,
	0x4e, 0x17, 0x2a, 0xe1, 0x92, 0xc0, 0x99, 0x6e, 0x74, 0xf4, 0xd0, 0xd2, 0x9f, 0x1e, 0x9e, 0x54,
	0x26, 0xa5, 0x85, 0x4f, 0x35, 0xaa, 0xed, 0x42, 0x45, 0x5c, 0xe2, 0xb8, 0x62, 0x48, 0x1b, 0x9f,
	0x31, 0x68, 0x8a, 0x49, 0xb1, 0xd3, 0xc9, 0xe9, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18,
	0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5,
	0x18, 0xa2, 0x34, 0x90, 0xc2, 0x18, 0x6c, 0x1e, 0x94, 0x2c, 0xb3, 0xd4, 0xaf, 0xd0, 0x87, 0xe5,
	0x49, 0x50, 0x48, 0x27, 0xb1, 0x81, 0x33, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x0e,
	0x68, 0x15, 0xaa, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterVeContractReward(ctx context.Context, in *MsgRegisterVeContractReward, opts ...grpc.CallOption) (*MsgRegisterRewardResponse, error)
	RegisterNProtocolReward(ctx context.Context, in *MsgRegisterNProtocolReward, opts ...grpc.CallOption) (*MsgRegisterRewardResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterVeContractReward(ctx context.Context, in *MsgRegisterVeContractReward, opts ...grpc.CallOption) (*MsgRegisterRewardResponse, error) {
	out := new(MsgRegisterRewardResponse)
	err := c.cc.Invoke(ctx, "/evmos.v9.reward.Msg/RegisterVeContractReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterNProtocolReward(ctx context.Context, in *MsgRegisterNProtocolReward, opts ...grpc.CallOption) (*MsgRegisterRewardResponse, error) {
	out := new(MsgRegisterRewardResponse)
	err := c.cc.Invoke(ctx, "/evmos.v9.reward.Msg/RegisterNProtocolReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterVeContractReward(context.Context, *MsgRegisterVeContractReward) (*MsgRegisterRewardResponse, error)
	RegisterNProtocolReward(context.Context, *MsgRegisterNProtocolReward) (*MsgRegisterRewardResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterVeContractReward(ctx context.Context, req *MsgRegisterVeContractReward) (*MsgRegisterRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVeContractReward not implemented")
}
func (*UnimplementedMsgServer) RegisterNProtocolReward(ctx context.Context, req *MsgRegisterNProtocolReward) (*MsgRegisterRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNProtocolReward not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterVeContractReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterVeContractReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterVeContractReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.v9.reward.Msg/RegisterVeContractReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterVeContractReward(ctx, req.(*MsgRegisterVeContractReward))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterNProtocolReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterNProtocolReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterNProtocolReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.v9.reward.Msg/RegisterNProtocolReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterNProtocolReward(ctx, req.(*MsgRegisterNProtocolReward))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.v9.reward.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVeContractReward",
			Handler:    _Msg_RegisterVeContractReward_Handler,
		},
		{
			MethodName: "RegisterNProtocolReward",
			Handler:    _Msg_RegisterNProtocolReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reward/tx.proto",
}

func (m *MsgRegisterVeContractReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterVeContractReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterVeContractReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BlockRewardShares.Size()
		i -= size
		if _, err := m.BlockRewardShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.GasFeeShares.Size()
		i -= size
		if _, err := m.GasFeeShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterNProtocolReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterNProtocolReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterNProtocolReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BlockRewardShares.Size()
		i -= size
		if _, err := m.BlockRewardShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.GasFeeShares.Size()
		i -= size
		if _, err := m.GasFeeShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterVeContractReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.GasFeeShares.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.BlockRewardShares.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterNProtocolReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.GasFeeShares.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.BlockRewardShares.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterVeContractReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterVeContractReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterVeContractReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasFeeShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasFeeShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockRewardShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockRewardShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterNProtocolReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterNProtocolReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterNProtocolReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasFeeShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasFeeShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockRewardShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockRewardShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
